receivers:
  # Menerima telemetri dengan protokol OTLP standar (gRPC port 4317, HTTP port 4318)
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # 1. Mengelompokkan data secara massal untuk menghemat penggunaan CPU dan jaringan
  batch:
    timeout: 1s
    send_batch_size: 256

  # 2. Filter: Membuang trace rute tidak penting agar tidak memenuhi memori
  filter/drop_unwanted:
    error_mode: ignore
    traces:
      span:
        - 'attributes["http.target"] == "/favicon.ico"'
        - 'attributes["http.target"] == "/healthz"'

  # 3. Transform: Menyamarkan (scrub) nilai password dalam atribut body request
  transform/scrub_sensitive:
    error_mode: ignore
    trace_statements:
      - context: span
        statements:
          # Mencari pola "password":"nilai" di dalam JSON string http.request.body dan menggantinya dengan [REDACTED]
          - replace_pattern(attributes["http.request.body"], "password\":\"[^\"]+\"", "password\":\"[REDACTED]\"")

# exporters:
#   # Mengirim data yang sudah bersih ke Zipkin menggunakan Zipkin Exporter
#   zipkin:
#     endpoint: "http://zipkin:9411/api/v2/spans"

exporters:
  # Kirim data ke OpenObserve via OTLP/HTTP
  otlphttp/openobserve:
    endpoint: "http://openobserve:5080/api/3IUF21iTO0OFVgH44ExKL7u0jky"
    headers:
      Authorization: Basic ZGVmYXVsdDpvMm9pX1VtWTA5dkxodjN3YWtCQTNEaGJWZnJKa0hrdVJPQVRi
      stream-name: express_stream
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, filter/drop_unwanted, transform/scrub_sensitive]
      exporters: [otlphttp/openobserve] # <-- Mengarah ke OpenObserve
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/openobserve] # <-- Mengaktifkan ingestion Logs
